# Site
repository: Git repository where your resume will be hosted, only required if you are hosting on GitHub (eg. sproogen/modern-resume-theme)
# favicon: Directory of your favicon (eg. images/favicon.ico)(optional)

# Content configuration version
version: 2

# Personal info
name: Jason Li
title: Principal Consultant
email: xiao.jason.li@gmail.com
# email_title: Email (Email title override)
phone: 0212359097
# phone_title: Phone (Phone title override)
website: xiao-jason-li.medium.com
# website_title: Web (Website title override)

# Dark Mode (true/false/never)
darkmode: false

# Social links
github_username:  shin-akuma
linkedin_username: jason-xiao-li

# Additional icon links
#additional_links:
#- title: Link name
#  icon: Font Awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
#  url: Link url (eg. https://google.com)
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
about_title: About Me
about_profile_image: images/profile.jfif
about_content: | # this will include new lines to allow paragraphs
  I’m a seasoned Cloud Specialist with a strong focus on delivering tangible business outcome with tailor made cloud solutions. I bring with me a wealth of knowledge and experience in <mark>Cloud Adoption</mark>, <mark>Cloud Native Development</mark>, <mark>Application Optimisation</mark> and <mark>Platform Engineering</mark>. My track records span from Corporate, Public Sector, FSI, Consultancy to ISV. Recently been wearing Principal Consultant and Azure Practice Lead hats, I provide thought leadership and DevSecOps best practices to both my team and my clients.

content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        border: weak  # Value of `weak` will display a weak border below this item. # Any 
                      # other value (or no value) means no border will be displayed
        title: ITSM Integration With Azure ESLZ, Cloud Deployment and IAM
        quote: >
          Most recent project
        description: | # this will include new lines to allow paragraphs
          Integrated client's Enterprise Landing Zone, IaC Deployment and Persona Based IAM Framework with their ServiceNow Systems, from both tooling and process persepctives. So that subscription vending, infrastructure deployment and access provisioning/deprovisoning become part of IT Service Catelogue and can be requested and consumed by divisional teams seamlessly
  - title: Experience
    layout: list
    content:
      - layout: left
        title: Sourced Group an Amdocs Company
        sub_title: Principal Consultant
        caption: November 2022 - present
        link: https://www.sourcedgroup.com/
        quote: >
          Principal Cloud Consultant
        description: |
          Being a Principal Consultant, I'm responsible for the delivery and growth of our key accounts. For the one which I've been the site lead from the beginning, an initial Well Architected Framework assessment turned into a program of work that has lasted for more than 18 months and consists of 6 SoWs and 2 parallel streams. We manage to significantly improve their Cloud ROI by uplifting tools, processes, and people capabilities. Client Satisfaction has constantly been at the top. 
          I'm also part of the Azure Practice Leadership and have led the development of multiple Azure offerings including Enterprise Scale Landing Zone, FinOps Framework, and OpenAI accelerator. I also organised regular mentoring sessions and Azure cert jam for our internal consultants to improve their capability in Azure space.
      - layout: left
        title: LAB3
        sub_title: Principal Consultant
        caption: October 2021 - November 2022
        link: https://www.lab3.com.au/
        quote: >
          Principal Azure Consultant
        description: |
          As a principal consultant at Lab3, my main responsibility is to own the end-to-end delivery of a solution. Solution can either be a client engagement, or one phase in a larger program of work, or a feature of an internal product. I'm responsible for leading a small squad consisting of developers and DevOps engineers. I have basically been wearing the hats of pre-sale consultant, scrum master, technical escalation point, cheerleader and the one managing expectations of external clients, internal client executives and product owners for the team. 
          I'm often the designer of the solution and the one with a holistic understanding of the problem we are trying to solve. I hold very close relationships with my teammates, I understand their strength, their challenges. their work (and life) priority and their career ambition through regular catch-ups and Agile ceremonies. Another part of my job is to be the trustworthy non-sales person to address client's concerns and enquiries throughout the engagement. I also very often roll-up my sleeves and contribute to the codebase, reason being I always make sure my teammates get the most rewarding and interesting tasks, while I play the role of concrete laying or drainage unblocking.
      - layout: left
        title: Leaven (Spark Business Group)
        sub_title: Cloud DevOps Tech Lead
        caption: July 2019 - October 2021
        link: https://concepts.co.nz/
        quote: >
          Cloud DevOps Tech Lead
        description: |
          Leading high-profile engagements ranging from Cloud migration, Application modernisation to Middleware development:
          •	2 of my projects entered Microsoft Partners Awards finalists. 
          •	2 nominated for Reseller Innovation Awards
          
          Escalation point for technical issues within Azure practice
          Mentoring and providing technical guidance to peers
          Steering internal product development which are currently co-selling with Microsoft NZ
      - layout: left
        title: Cin7
        sub_title: DevOps Manager
        caption: May 2018 - July 2019
        link: https://cin7.com/
        quote: >
          Started as Senior SRE, later promoted to DevOps Manager
        description: |
          A key player in a milestone project that migrated the entire Cin7 infrastructure from Datacentre to Azure which includes Terabytes of data, tens of VMs, and a number of mission critical applications. All of which was completed under 6 hours with minimum user impact.
          Started the initiative of “template everything when possible, script everything when possible”
          Continuously improving the Azure Infrastructure Design post migration and slowly moving towards PaaS
          Introduced Custom Build Tasks to Cin7’s CD pipelines; achieved zero-downtime deployment
          Acted as a communication hub between MS Fast-track team, Partners and internal stakeholders during and after Cloud Migration; hosted technical discussions, weekly catch-ups and solution design presentations
          Mentoring Developers and teammates on Azure and DevOps subjects
          Contributing to Code Quality Control and General Bug-fixing
          Promoted to the newly created DevOps Manager role to take the ownership of the DevOps team (used to be under the direct management of CIO)
          Manage all the available resources including internal team members, vendors and partners to ensure the platform is tuned to run at the highest level of performance.
          Support the product and engineering teams so that high quality code is shipped to production promptly and seamlessly.
          Grow the team both vertically and horizontally to cope with the rapidly increasing customer base.
  - title: Education
    layout: list
    content:
      - layout: top
        title: The University of Auckland
        sub_title: Master of Science with Honours (Computer Science)
        caption: 2013 - 2015
        quote: >
          Completed a thesis on Digial Identity Assurance
      - layout: top
        title: University of Canterbury
        sub_title: Postgraduate Diploma in Science with Distinction (Computer Security and Forensics)
        caption: 2010 - 2011
        quote: >
          Made to Dean's list twice in a row
  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      This is where you can write a little more about yourself. You could title this section **Interests** and include some of your other interests.

      Or you could title it **Skills** and write a bit more about things that make you more desirable, like *leadership* or *teamwork*

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
# remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

exclude : [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
  ]
